### ISSUE TITLE
Can you add our CVPR2023 paper "Generic-to-Specific Distillation of Masked Autoencoders" to the list

### ISSUE THREAD

**Issue by pengzhiliang** [DWCTOD/CVPR2021-Papers-with-Code-Demo#10]
Paper title: Generic-to-Specific Distillation of Masked Autoencoders
Paper link: https://arxiv.org/abs/2302.14771
Code link: https://github.com/pengzhiliang/G2SD

This paper can be categorized into "Knowledge Distillation " or "Masked Autoencoders".
Thank you!

**Comment by DWCTOD** [comment]
Received,thanks
