### ISSUE TITLE
Please add our CVPR 2023 paper on 3D Semantic Segmentation and Point Cloud

### ISSUE THREAD

**Issue by kts707** [DWCTOD/CVPR2021-Papers-with-Code-Demo#12]
Hi, could you add our CVPR2023 paper on 3D Semantic Segmentation and Point Cloud? Thanks!

Title: Self-Supervised Image-to-Point Distillation via Semantically Tolerant Contrastive Loss
Link: https://arxiv.org/abs/2301.05709

**Comment by DWCTOD** [comment]
Received,thanks
