### ISSUE TITLE
Please add our CVPR2023 paper about depth estimation

### ISSUE THREAD

**Issue by noahzn** [DWCTOD/CVPR2021-Papers-with-Code-Demo#14]
Hi, could you add our paper about self-supervised depth estimation?
Title: Lite-Mono: A Lightweight CNN and Transformer Architecture for Self-Supervised Monocular Depth Estimation
Link: https://arxiv.org/abs/2211.13202
Code: https://github.com/noahzn/Lite-Mono

Thanks.

**Comment by DWCTOD** [comment]
Received,thanks
