### ISSUE TITLE
Please add our CVPR 2023 paper about video generation with diffusion models

### ISSUE THREAD

**Issue by nihaomiao** [DWCTOD/CVPR2021-Papers-with-Code-Demo#15]
Hi, @DWCTOD,

Thanks very much for your efforts to collect these papers! I am wondering whether you can add our CVPR 2023 paper:

Title: Conditional Image-to-Video Generation with Latent Flow Diffusion Models
Paper link: https://arxiv.org/pdf/2303.13744.pdf
Code Link: https://github.com/nihaomiao/CVPR23_LFDM

Thanks a lot!

**Comment by DWCTOD** [comment]
Received,thanks
