### ISSUE TITLE
Please add our CVPR 2023 paper about self-supervised pre-trained model

### ISSUE THREAD

**Issue by cwhgn** [DWCTOD/CVPR2021-Papers-with-Code-Demo#18]
Hi, @DWCTOD,

Could you please add our CVPR 2023 paper to the list:

Title: Beyond Appearance: a Semantic Controllable Self-Supervised Learning Framework for Human-Centric Visual Tasks
Paper link: https://arxiv.org/abs/2303.17602
Project Link: https://github.com/tinyvision/SOLIDER

Thanks a lot!

**Comment by DWCTOD** [comment]
Received,thanks
