### ISSUE TITLE
Please add our CVPR2023 paper DexArt to Robotics

### ISSUE THREAD

**Issue by Kami-code** [DWCTOD/CVPR2021-Papers-with-Code-Demo#20]
Here is our CVPR2023 paper: DexArt: Benchmarking Generalizable Dexterous Manipulation with Articulated Objects

Code: https://github.com/Kami-code/dexart-release
Homepage: https://www.chenbao.tech/dexart/

**Comment by DWCTOD** [comment]
Received,thanks
