### ISSUE TITLE
Please add our CVPR2024 paper MP5: A Multi-modal Open-ended Embodied Agent

### ISSUE THREAD

**Issue by IranQin** [DWCTOD/CVPR2021-Papers-with-Code-Demo#21]
Name: MP5: A Multi-modal Open-ended Embodied System in Minecraft via Active Perception
Paper: https://arxiv.org/abs/2312.07472
Code: https://github.com/IranQin/MP5
Website: https://iranqin.github.io/MP5.github.io/

**Comment by DWCTOD** [comment]
Received, thank you
