### ISSUE TITLE
Please add a CVPR 2024 paper, Logit Standardization in Knowledge Distillation.

### ISSUE THREAD

**Issue by sunshangquan** [DWCTOD/CVPR2021-Papers-with-Code-Demo#22]
Arxiv: https://arxiv.org/abs/2403.01427
Github: https://github.com/sunshangquan/logit-standardization-KD

**Comment by BarqueroGerman** [comment]
Paper name/title: Seamless Human Motion Composition with Blended Positional Encodings
Paper link: https://arxiv.org/abs/2402.15509
Code link: https://github.com/BarqueroGerman/FlowMDM

**Comment by DWCTOD** [comment]
Received,thanks
