### ISSUE TITLE
Please add a CVPR 2024 paper on depth estimation, thanks!

### ISSUE THREAD

**Issue by Junda24** [DWCTOD/CVPR2021-Papers-with-Code-Demo#24]
paper name : AFNet: Adaptive Fusion of Single-View and Multi-View Depth for Autonomous Driving
arxiv: https://arxiv.org/pdf/2403.07535.pdf
code: https://github.com/Junda24/AFNet

**Comment by DWCTOD** [comment]
Received,thanks
