### ISSUE TITLE
Please add a CVPR 2024 paper on object detection, thanks!

### ISSUE THREAD

**Issue by xiuqhou** [DWCTOD/CVPR2021-Papers-with-Code-Demo#25]
paper name : Salience DETR: Enhancing Detection Transformer with Hierarchical Salience Filtering Refinement
arxiv: https://arxiv.org/abs/2403.16131
code: https://github.com/xiuqhou/Salience-DETR

**Comment by DWCTOD** [comment]
Received,thanks
