### ISSUE TITLE
Please add a CVPR 2024 paper on 其他/Other, thanks!

### ISSUE THREAD

**Issue by pureexe** [DWCTOD/CVPR2021-Papers-with-Code-Demo#26]
Paper name : DiffusionLight: Light Probes for Free by Painting a Chrome Ball
Arxiv: https://arxiv.org/abs/2312.09168
Code: https://github.com/DiffusionLight/DiffusionLight
Website: https://diffusionlight.github.io/

Note that, DiffusionLight is a work on Lighting Estimation. So, it should be categorized at [其他/Other](https://github.com/DWCTOD/CVPR2024-Papers-with-Code-Demo#Other) in your list.

**Comment by DWCTOD** [comment]
Received,thanks
