### ISSUE TITLE
Please add CVPR 2024 paper "Hourglass Tokenizer for Efficient Transformer-Based 3D Human Pose Estimation"

### ISSUE THREAD

**Issue by Vegetebird** [DWCTOD/CVPR2021-Papers-with-Code-Demo#27]
Paper title: Hourglass Tokenizer for Efficient Transformer-Based 3D Human Pose Estimation
Paper link: https://arxiv.org/pdf/2311.12028.pdf
Code link: https://github.com/NationalGAILab/HoT

**Comment by DWCTOD** [comment]
Received,thanks
