### ISSUE TITLE
Add a new paper

### ISSUE THREAD

**Issue by BinhuiXie** [DWCTOD/CVPR2021-Papers-with-Code-Demo#4]
Hello, @DWCTOD 

Please add our new paper RIPU to this repo.

Title: Towards Fewer Annotations: Active Learning via Region Impurity and Prediction Uncertainty for Domain Adaptive Semantic Segmentation

paper: https://arxiv.org/pdf/2111.12940.pdf
code: https://github.com/BIT-DA/RIPU

Thank you!

**Comment by DWCTOD** [comment]
received，thanks
