### ISSUE TITLE
Please add our Oral paper on Knowledge Distillation of 3D object detection

### ISSUE THREAD

**Issue by Vegeta2020** [DWCTOD/CVPR2021-Papers-with-Code-Demo#8]
Could you help to add the paper the list?

Paper (Oral): Boosting 3D Object Detection by Simulating Multimodality on Point Clouds
Paper Link: https://arxiv.org/abs/2206.14971

Thanks!

**Comment by DWCTOD** [comment]
Got it! Thanks!
