### ISSUE TITLE
Please add our cvpr23 paper "PolyFormer: Referring Image Segmentation as Sequential Polygon Generation”

### ISSUE THREAD

**Issue by joellliu** [DWCTOD/CVPR2021-Papers-with-Code-Demo#9]
Hi,

Can you add our paper "PolyFormer: Referring Image Segmentation as Sequential Polygon Generation"
[https://arxiv.org/abs/2302.07387](https://arxiv.org/abs/2302.07387) to the list? It's about vision-language multi-modal learning and instance segmentation. Thank you!

**Comment by DWCTOD** [comment]
Received,thanks
